version: '3.5'

services:
  patient:
    container_name: painkiller-patient
    build: patient
    ports:
      - "8080:8000"
    env_file:
      - .env
    depends_on:
      - database

  measurement:
    container_name: painkiller-measurement
    build: measurement
    ports:
      - "8081:8000"
    env_file:
      - .env
    depends_on:
      - database

  database:
    container_name: painkiller-database
    image: postgres
    environment:
      POSTGRES_USER: painkiller
      POSTGRES_PASSWORD: painkiller123
      PGDATA: /data/postgres
    volumes:
      - .postgres:/data/postgres
    ports:
      - "5432:5432"

  filesystem:
    container_name: painkiller-filesystem
    image: quay.io/minio/minio:RELEASE.2023-07-07T07-13-57Z
    command: server --console-address ":9001" /data/minio/
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: painkiller
      MINIO_ROOT_PASSWORD: painkiller123
