version: '3.5'

services:
  patient:
    container_name: painkiller-patient
    build: patient
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - database

  database:
    container_name: painkiller-database
    image: postgres
    environment:
      POSTGRES_USER: painkiller
      POSTGRES_PASSWORD: painkiller123
      PGDATA: /data/postgres
    volumes:
      - .postgres:/data/postgres
    ports:
      - "5432:5432"
