FROM python:3.10-alpine

WORKDIR /app

COPY . .

RUN pip install . --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple/

CMD ["uvicorn", "patient.main:app", "--host", "0.0.0.0", "--port", "8000"]